[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
cross_chain_escrow_dst = "B9SnVJbXNd6RFNxHqPkTvdr46YPT17xunemTQfDsCNzR"
cross_chain_escrow_src = "6NwMYeUmigiMDjhYeYpbxC6Kc63NzZy1dfGd7fGcdkVS"
dutch_auction_taking_amount = "6Y87E6QNyrsVZbQSRapcYcXUi9fpFrMiC16C5nLmCCHV"
mocks = "5Jvn87vo6XzejGMBhTss4kYDJC7D7JxkKuN3zG1fZnk6"
non_custodial_escrow = "AKEVm47qyu5E2LgBDrXifJjS2WJ7i4D1f9REzYvJEsLg"
trading_program = "8BLa8hpRVLWCkqyD7X5JeSB1xRnct9QumUDghe3UjeTf"
whitelist_validator = "3zPcYCrngDJQjzTd7vN1povXWtxwKR1BbofWoaHYxPhv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
